# Generated by Django 4.2.7 on 2025-08-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Склад/Подразделение',
                'verbose_name_plural': 'Склады/Подразделения',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название операции')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
                'db_table': 'part_type',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'user_job',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('partonymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userjob', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название узла')),
                ('decimal_num', models.CharField(max_length=255, verbose_name='Децимальный номер')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.part', verbose_name='Родительский узел')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parttype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Модель/Узел',
                'verbose_name_plural': 'Модели/Узлы',
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('time', models.DateTimeField(verbose_name='Дата/время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device', verbose_name='Устройство')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Место проведения')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operation', verbose_name='Операция')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Записи журнала',
                'db_table': 'journal',
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.part', verbose_name='Модель'),
        ),
    ]
