# Generated by Django 4.2.7 on 2025-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='part',
        ),
        migrations.AddField(
            model_name='device',
            name='parts',
            field=models.ManyToManyField(blank=True, to='main.part', verbose_name='Модели/Узлы'),
        ),
    ]
